name: module_layout
description: "A new Flutter project."
publish_to: 'none' # Jangan ubah ini kecuali Anda akan mempublikasikan paket ini ke pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Versi Dart SDK Anda (3.7.2) sudah kompatibel dengan ini

dependencies: # Ini adalah satu-satunya blok dependencies yang seharusnya ada
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  firebase_core: ^2.30.0 # Diperbarui ke versi stabil terbaru (sebelumnya 2.29.0)
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  intl: ^0.19.0 # Diperbarui ke versi stabil terbaru (sebelumnya 0.18.1)
  provider: ^6.1.2 # Diperbarui ke versi stabil terbaru (sebelumnya 6.0.5)
  rflutter_alert: ^2.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/