// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVCq7IIX1M4XA_mhxkDJuSdXR2mhHCu6s',
    appId: '1:248447428468:web:c9098ef10369eee9926e21',
    messagingSenderId: '248447428468',
    projectId: 'modulelayout',
    authDomain: 'modulelayout.firebaseapp.com',
    storageBucket: 'modulelayout.firebasestorage.app',
    measurementId: 'G-L85LGGP3WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAViSqebolmpaWJWHwq9VuMcMXflukGgVM',
    appId: '1:248447428468:android:85f262573ed61789926e21',
    messagingSenderId: '248447428468',
    projectId: 'modulelayout',
    storageBucket: 'modulelayout.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk4Rh12_n9e7MyLQtRjysVe3J7E_FwG3I',
    appId: '1:248447428468:ios:99e3125e037b887f926e21',
    messagingSenderId: '248447428468',
    projectId: 'modulelayout',
    storageBucket: 'modulelayout.firebasestorage.app',
    iosBundleId: 'com.example.moduleLayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk4Rh12_n9e7MyLQtRjysVe3J7E_FwG3I',
    appId: '1:248447428468:ios:99e3125e037b887f926e21',
    messagingSenderId: '248447428468',
    projectId: 'modulelayout',
    storageBucket: 'modulelayout.firebasestorage.app',
    iosBundleId: 'com.example.moduleLayout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVCq7IIX1M4XA_mhxkDJuSdXR2mhHCu6s',
    appId: '1:248447428468:web:20beadd81a048078926e21',
    messagingSenderId: '248447428468',
    projectId: 'modulelayout',
    authDomain: 'modulelayout.firebaseapp.com',
    storageBucket: 'modulelayout.firebasestorage.app',
    measurementId: 'G-20DGX9QWSN',
  );
}
